name: Publish NextJS Site

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-react-to-ghp@v1.2.0
      with:
        path: out
        build_command: npm run export
